### ISSUE TITLE
only closing issue with screens

### ISSUE THREAD

**Issue by Bohemi1977** [starkillerOG/motion-blinds#31]
Hello,

I would like to report een issue.
I successfully integrated the Brel hub with Home assistant and the aim is to control 2 bi-directional motors that are connected to it. (these are sunscreens that open and close, up/down)
When adding the devices to the dashboard, I only have the option to close or stop the screens, not to open them.

I also see this repeating message in the logging:
2022-12-19 02:37:35.456 ERROR (SyncWorker_5) [motionblinds.motion_blinds] Device with mac '@@@@@@@@0001' has wireless_mode '4' that is not yet known, please submit an issue at https://github.com/starkillerOG/motion-blinds/issues.
2022-12-19 02:37:35.472 ERROR (SyncWorker_5) [motionblinds.motion_blinds] Device with mac '@@@@@@@@0003' has wireless_mode '4' that is not yet known, please submit an issue at https://github.com/starkillerOG/motion-blinds/issues.

**Comment by Bohemi1977** [comment]
Is there no activity anymore on this project?

**Comment by Bohemi1977** [comment]
@starkillerOG are you still active?

**Comment by starkillerOG** [comment]
@Bohemi1977 yes I am still active, only a bit busy over the holidays.
What is the exact model of the sunscreen/motors?
The wireless_mode '4' is not documented in the API.
0 = uni-direction
1 = bi-direction
2 = bi-direction (mechanical limits)
3 = others

How does the sunscreen look in the Brel app, are you able to set a position, or only move up/down/stop?
Does the brel app show the current position of these blinds?

**Comment by Bohemi1977** [comment]
I will ask details about the motors and the mode because I can't see this.
The sunscreens only have the close/stop/open button. There is no indicator of the position.

**Comment by starkillerOG** [comment]
@Bohemi1977 could you also try running the following python code (fill in IP and KEY, install motionblinds using pip3 install --upgrade motionblinds):
```
import logging
logging.basicConfig(level=logging.DEBUG, format='%(message)s')

from motionblinds import MotionGateway
m = MotionGateway(ip="192.168.1.IP", key="KEYKEYKEY")

m.GetDeviceList()
m.Update()

for blind in m.device_list.values():
    blind.Update()
    print(blind)
```

It will help me see the response of your blinds.

**Comment by Bohemi1977** [comment]
i never used python but i think i got it working.

i get an error when loading your script, not sure if i am doing something wrong.

Logger: custom_components.pyscript.file.blindstest
Source: custom_components/pyscript/global_ctx.py:337 
Integration: Pyscript Python scripting (documentation, issues) 
First occurred: 04:19:13 (7 occurrences) 
Last logged: 04:28:05

Exception in </config/pyscript/blindstest.py> line 1: import logging ^ ModuleNotFoundError: import of logging not allowed
Exception in </config/pyscript/blindstest.py> line 7: m.GetDeviceList() ^ gaierror: [Errno -2] Name does not resolve

**Comment by Bohemi1977** [comment]
When i try to run the script in the editor i still get the error related to ModuleNotFoundError, this is the message:

Exception has occurred: ModuleNotFoundError
No module named 'motionblinds'
  File "/config/pyscript/blindstest.py", line 4, in <module>
    from motionblinds import MotionGateway

**Comment by Bohemi1977** [comment]
I am a little further now with it i think knowing i have no issues anymore on line 1 and 7 of the script but on line 11.
i get this message from the script:

> Logger: custom_components.pyscript.file.blindstest
> Source: custom_components/pyscript/global_ctx.py:337 
> Integration: Pyscript Python scripting ([documentation](https://github.com/custom-components/pyscript), [issues](https://github.com/custom-components/pyscript/issues)) 
> First occurred: 01:40:21 (1 occurrences) 
> Last logged: 01:40:21
> 
> Exception in </config/pyscript/blindstest.py> line 11: blind.Update() ^ TimeoutError: timed out

And this message from the Motion Blinds integration that is related to it i think:

> Logger: motionblinds.motion_blinds
> Source: custom_components/pyscript/eval.py:1906 
> Integration: Pyscript Python scripting ([documentation](https://github.com/custom-components/pyscript), [issues](https://github.com/custom-components/pyscript/issues)) 
> First occurred: 01:37:32 (10 occurrences) 
> Last logged: 01:40:21
> 
> Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20221230004000797', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'msgID': '20221230014000496', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
> Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20221230004005893', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'msgID': '20221230014005617', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
> Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20221230004011015', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'msgID': '20221230014010736', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
> Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20221230004016134', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'msgID': '20221230014015859', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
> Timeout of 5.0 sec occurred on 5 attempts while waiting on multicast push from update request, communication between gateway and blind might be bad.

i am running Firmware: A1.0.3_B0.1.2, protocol: 0.9

**Comment by starkillerOG** [comment]
@Bohemi1977 I got a response from the manufacturer, telling me wireless mode 4 is a VirtualPercentageLimits motor.
It means it has bidirection communication to the hub, but it does not have a motor encoding, only mechanical limits.
Once both mechanical limits are set and found by the motor, it schould start providing position information and you schould be able to set the position of the motor in %.
The motor does this by timing the run-time from the limits.
This is however not as acurate as a encoded motor, but the best the motor can do.

I just released version 0.6.14 of the upstreams motionblinds library: https://github.com/starkillerOG/motion-blinds/releases
Which schould have proper support for these types of motors.

**Comment by starkillerOG** [comment]
@Bohemi1977 This HomeAssistant PR will hopefully fix your issues: https://github.com/home-assistant/core/pull/84873

If you appreciate the Motion Blinds integration, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.

**Comment by starkillerOG** [comment]
@Bohemi1977 the output from the python test script would still be helpfull to check some things.
The error in your last post indicates that the key you supplied is wrong.
Can you check the key?

**Comment by Bohemi1977** [comment]
> @Bohemi1977 the output from the python test script would still be helpfull to check some things.
> The error in your last post indicates that the key you supplied is wrong.
> Can you check the key?

Where can i find that output? sorry for my bounded knowledge

**Comment by starkillerOG** [comment]
@Bohemi1977 I mean if you run the script succesfully and post the response here ;)
Are you able to set the position (for example 25%) in the Brel app or HomeAssistant?

Does your motor indeed have a top and bottom mechanical limit you can set?
Did you already let the motor run untill it reached the set mechanical limits, for both limits?
Once the motor knows the position of both mechanical limits, you schould be able to control the position directly...

**Comment by Bohemi1977** [comment]
Can you check the key?
Yes, it is the same as in the Brel app. The same key I used to connect the integration.

This is the output i see when i run the script in ssh:

>   OS Version:               Home Assistant OS 9.4
>   Home Assistant Core:      2022.12.8
> 
>   Home Assistant URL:       http://homeassistant.local:8123
>   Observer URL:             http://homeassistant.local:4357
> ➜  ~ python3 /config/pyscript/blindstest.py
> Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20221230221103514', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'msgID': '20221230231102569', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
> Timeout of 5.0 sec occurred at 1 attempts while waiting on multicast push from update request, trying again...
> Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20221230221108531', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'msgID': '20221230231107666', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
> Timeout of 5.0 sec occurred at 2 attempts while waiting on multicast push from update request, trying again...
> Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20221230221113628', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'msgID': '20221230231112786', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
> Timeout of 5.0 sec occurred at 3 attempts while waiting on multicast push from update request, trying again...
> Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20221230221118749', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'msgID': '20221230231117906', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
> Timeout of 5.0 sec occurred at 4 attempts while waiting on multicast push from update request, trying again...
> Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20221230221123863', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'msgID': '20221230231123129', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
> Timeout of 5.0 sec occurred on 5 attempts while waiting on multicast push from update request, communication between gateway and blind might be bad.
> Traceback (most recent call last):
>   File "/config/pyscript/blindstest.py", line 11, in <module>
>     blind.Update()
>   File "/usr/lib/python3.10/site-packages/motionblinds/motion_blinds.py", line 1270, in Update
>     mcast_response = self._wait_on_mcast_report(mcast)
>   File "/usr/lib/python3.10/site-packages/motionblinds/motion_blinds.py", line 976, in _wait_on_mcast_report
>     mcast_data, (ip, _) = mcast_socket.recvfrom(SOCKET_BUFSIZE)
> TimeoutError: timed out

Are you able to set the position (for example 25%) in the Brel app or HomeAssistant?
I am not able to set the position in the Brel app or HomeAssistant. only open/stop/close in Brel app and open/stop in HA.

Does your motor indeed have a top and bottom mechanical limit you can set?
I have set my mechanical limits with a red screwdriver that was with the motors. 

Did you already let the motor run untill it reached the set mechanical limits, for both limits?
Yes, i have reached the limits on both because when I open them, I let them run until they reach the limit, the same with closing.

Once the motor knows the position of both mechanical limits, you schould be able to control the position directly...
I really don't know why

**Comment by Bohemi1977** [comment]
After a HA restart i see some other messages exactly about mechanical limits via SSH

> ➜  ~ python3 /config/pyscript/blindstest.py
> Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20221230221103514', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'msgID': '20221230231102569', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
> Timeout of 5.0 sec occurred at 1 attempts while waiting on multicast push from update request, trying again...
> Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20221230221108531', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'msgID': '20221230231107666', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
> Timeout of 5.0 sec occurred at 2 attempts while waiting on multicast push from update request, trying again...
> Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20221230221113628', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'msgID': '20221230231112786', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
> Timeout of 5.0 sec occurred at 3 attempts while waiting on multicast push from update request, trying again...
> Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20221230221118749', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'msgID': '20221230231117906', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
> Timeout of 5.0 sec occurred at 4 attempts while waiting on multicast push from update request, trying again...
> Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20221230221123863', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': 'ac67b244199c0001', 'deviceType': '10000000', 'msgID': '20221230231123129', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
> Timeout of 5.0 sec occurred on 5 attempts while waiting on multicast push from update request, communication between gateway and blind might be bad.
> Traceback (most recent call last):
>   File "/config/pyscript/blindstest.py", line 11, in <module>
>     blind.Update()
>   File "/usr/lib/python3.10/site-packages/motionblinds/motion_blinds.py", line 1270, in Update
>     mcast_response = self._wait_on_mcast_report(mcast)
>   File "/usr/lib/python3.10/site-packages/motionblinds/motion_blinds.py", line 976, in _wait_on_mcast_report
>     mcast_data, (ip, _) = mcast_socket.recvfrom(SOCKET_BUFSIZE)
> TimeoutError: timed out
> ➜  ~ python3 /config/pyscript/blindstest.py
> Device with mac 'ac67b244199c0001' reported voltage '220.0' outside of expected limits, got raw voltage: '22000'
> Virtual percentage motor with mac 'ac67b244199c0001' has mechanical limit status 'NoLimitDetected', both mechanical limits need to be detected before percentage control can be used
> Device with mac 'ac67b244199c0001' reported voltage '220.0' outside of expected limits, got raw voltage: '22000'
> Virtual percentage motor with mac 'ac67b244199c0001' has mechanical limit status 'NoLimitDetected', both mechanical limits need to be detected before percentage control can be used
> <MotionBlind mac: ac67b244199c0001, type: RollerBlind, status: Stopped, position: None %, angle: None, limit: NoLimitDetected, battery: AC, 200.0 %, 220.0 V, RSSI: -49 dBm, com: VirtualPercentageLimits>
> Device with mac 'ac67b244199c0003' reported voltage '220.0' outside of expected limits, got raw voltage: '22000'
> Virtual percentage motor with mac 'ac67b244199c0003' has mechanical limit status 'NoLimitDetected', both mechanical limits need to be detected before percentage control can be used
> Device with mac 'ac67b244199c0003' reported voltage '220.0' outside of expected limits, got raw voltage: '22000'
> Virtual percentage motor with mac 'ac67b244199c0003' has mechanical limit status 'NoLimitDetected', both mechanical limits need to be detected before percentage control can be used
> <MotionBlind mac: ac67b244199c0003, type: RollerBlind, status: Stopped, position: None %, angle: None, limit: NoLimitDetected, battery: AC, 200.0 %, 220.0 V, RSSI: -58 dBm, com: VirtualPercentageLimits>

**Comment by Bohemi1977** [comment]
The company who provided the screens told me that this type needed to be set directly at the motor to their end positions instead of by remote control. They or closed this week, i will ask them more details next week.

**Comment by Bohemi1977** [comment]
I just tried to set the limits in the Brel app and now I can see and change the position in the Brel app but not in Home Assistant. 
In the Brel app their name also automatically changed from Roller blinds to screens. In HA their name did not change.

This is the output i get from the script now:
> ➜  ~ python /config/pyscript/blindstest.py 
> Device with mac 'ac67b244199c0001' reported voltage '220.0' outside of expected limits, got raw voltage: '22000'
> Device with mac 'ac67b244199c0001' reported voltage '220.0' outside of expected limits, got raw voltage: '22000'
> <MotionBlind mac: ac67b244199c0001, type: RollerBlind, status: Stopped, position: 0 %, angle: 0.0, limit: BothLimitsDetected, battery: AC, 200.0 %, 220.0 V, RSSI: -48 dBm, com: VirtualPercentageLimits>
> Device with mac 'ac67b244199c0003' reported voltage '220.0' outside of expected limits, got raw voltage: '22000'
> Device with mac 'ac67b244199c0003' reported voltage '220.0' outside of expected limits, got raw voltage: '22000'
> <MotionBlind mac: ac67b244199c0003, type: RollerBlind, status: Stopped, position: 0 %, angle: 0.0, limit: BothLimitsDetected, battery: AC, 200.0 %, 220.0 V, RSSI: -58 dBm, com: VirtualPercentageLimits>

**Comment by Bohemi1977** [comment]
All working fine now! 
I see it's normal now that the open button is greyed out  when the screen is open, and the close button is greyed out when the screen is closed.

I know it was probably mostly my missing of knowledge but big thanks!

**Comment by starkillerOG** [comment]
@Bohemi1977 

> After a HA restart i see some other messages exactly about mechanical limits via SSH

Yes I just implemented that warning message, to let users now they schould set the limits of the blind.

> I just tried to set the limits in the Brel app and now I can see and change the position in the Brel app but not in Home Assistant.

Very good to hear, after restarting HomeAssistant, the warning message about the limits schould now also be gone.
If you open the more-info pop-up in Homeassistant of the cover entity you schould now see a slider where you can control the position, is that true?

> I know it was probably mostly my missing of knowledge but big thanks!

No problem, these VertualPercentage motors were not supported properly yet, so I did make some nice improvements thanks to your feedback!
Also thanks for sponsering!

I would like to know if the position control is now also working in HomeAssistant, could you let me know?

I will fix the last error message:
`Device with mac 'ac67b244199c0001' reported voltage '220.0' outside of expected limits, got raw voltage: '22000'`
And then I think all errors schould be gone for you.

Have a happy new year!

**Comment by Bohemi1977** [comment]
Happy new year firs tof all!

I can see the position now. That is correct.
